development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: <%= ENV['MAX_THREADS'] || 25 %>
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: <%= ENV['MAX_THREADS'] || 25 %>
  timeout: 5000
